version: "2.1"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - HASHED_PASSWORD=${HASHED_PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE}
    volumes:
      - ./appdata/config:/config
    ports:
      - ${PORT}:8443
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy-code-server
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - DOMAIN=${PROXY_DOMAIN}
      - EMAIL=${ACME_EMAIL}    # The email address to use for ACME registration.
      - LOG_FILE=/data/access.log