version: '3'

services:

    joplin-db:
        image: postgres:13.1
        container_name: joplin-db
        volumes:
            - ${DATA_FOLDER}/data/postgres:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}

    joplin-app:
        image: joplin/server:latest
        container_name: joplin-app
        depends_on:
            - joplin-db
        ports:
            - "22300:22300"
        env_file: .env
        restart: unless-stopped
        environment:
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_HOST=joplin-db
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - MAILER_ENABLED=${MAILER_ENABLED}
            - MAILER_HOST=${MAILER_HOST}
            - MAILER_PORT=${MAILER_PORT}
            - MAILER_SECURE=${MAILER_SECURE}
            - MAILER_AUTH_USER=${MAILER_AUTH_USER}
            - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
            - MAILER_NOREPLY_NAME=${MAILER_NOREPLY_NAME}
            - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}
