version: '3.4'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SSL=${SMTP_SSL}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ${DATA_FOLDER}:/data

  caddy:
    image: caddy:2
    container_name: caddy-vaultwarden
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DATA_FOLDER}/caddy-config:/config
      - ${DATA_FOLDER}/caddy-data:/data
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${ACME_EMAIL}    # The email address to use for ACME registration.
      - LOG_FILE=/data/access.log
